### ISSUE TITLE
进入休眠后唤醒直接重启

### ISSUE THREAD

**Issue by klmchp** [lqsahut/strix_B460i_EFI#1]
is:issue is:open 用的是你这套EFI，主板配置一样，CPU是i5 10500，目前问题是进入休眠后唤醒直接重启，请问该如何配置？

**Comment by polarisink** [comment]
这个是我请人配置的，自己属于会用但是不会造轮子的那种，所以帮不了你哦。我自己没出过这个问题



发自我的iPhone&nbsp;se


------------------ 原始邮件 ------------------
发件人: Kevin Liu <notifications@github.com&gt;
发送时间: 2020年11月23日 21:35
收件人: lqsgoodboy/ROG_B460i_Hackintosh <ROG_B460i_Hackintosh@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[lqsgoodboy/ROG_B460i_Hackintosh] 进入休眠后唤醒直接重启 (#1)





 
is:issue is:open 用的是你这套EFI，主板配置一样，CPU是i5 10500，目前问题是进入休眠后唤醒直接重启，请问该如何配置？

**Comment by klmchp** [comment]
请教身边的人还是网上？

**Comment by fefz** [comment]
`DisableVariableWrite` 把这个值设置为`true`试试
